title: LoomState.fm
email: info@loomstate.fm
description: LoomState. An independent podcast network.
url: https://loomstate.fm
episode_base_url: https://cdn.loomstate.fm
twitter_username: loomstate
github_username: loomstate

collections:
  people:
    output: true
    permalink: /people/:path/

  shows:
    output: true
    permalink: /:path/

  feeds:
    output: true
    permalink: /:path/

  episodes:
    output: true
    permalink: /:path/

defaults:
  - scope:
      type: people
    values:
      layout: person

  - scope:
      type: shows
    values:
      layout: show
      author: LoomState.fm
      explicit: 'no'
      # For iTunes admin. This information is not displayed on the iTunes Store.
      owner_name: LoomState.fm
      owner_email: info@loomstate.fm
      # See https://help.apple.com/itc/podcasts_connect/#/itc9267a2f12 near the bottom for valid categories
      category: Technology
      sub_category: Software How-To
      copyright: Loom State Productions

  - scope:
      type: feeds
    values:
      layout: feed

  - scope:
      type: episodes
    values:
      layout: episode
      # The date must be “day-of-week, day month year”. The time must be in 24 hour format (no AM or PM) and must include the time zone offset.
      publish_date: Wed, 15 Jun 2014 19:00:00 GMT
      # This is your podcast episode file
      enclosure_url: null
      # The length attribute is the file size in bytes. Find this information in the properties of your podcast file (on a Mac, choose Get Info from the File menu and refer to the size row).
      enclosure_length: 8727310
      # for available types, see https://www.apple.com/itunes/podcasts/specs.html
      enclosure_type: audio/mpeg
      # HH:MM:SS,
      duration: 7:04

header_nav:
  - title: Shows
    url: /shows/
  - title: People
    url: /people/
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

footer_nav:
  - title: Home
    url: /
  - title: Shows
    url: /shows/
  - title: People
    url: /people/
  - title: Episodes
    url: /episodes/
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Build settings

gems:
  - octopress-autoprefixer

markdown: kramdown

include:
  - _pages

exclude:
  - README.md
  - LICENSE
  - node_modules
  - index.js
  - package.json
  - Gemfile
  - Gemilfe.lock
  - gulpfile.babel.js


# ----- For itunes.xml
# Ref: https://github.com/DevTips/Jekyll-Powered-Podcast-XML-Generator

# The homepage of your podcast
podcastSite: https://loomstate.fm/:show/

# The cover image for the podcast, will show in search results in iTunes
podcastCoverImg: https://loomstate.fm/imageSize1400x1400-min.jpg

# The name of your podcast
podcastTitle: My Podcast Title

# About You. For iTunes admin. This information is not displayed on the iTunes Store.
podcastOwner: Karl Bowden
podcastEmail: karl@loomstate.fm

# See https://www.apple.com/itunes/podcasts/specs.html near the bottom for valid categories
category: Education
subCategory: Higher Education

# is it too dangerous for the impressionable kiddos?
podcastIsExplicit: "no"

podcastAuthor: Org, brand or individual
podcastDescription: Verbose description of the podcast.
podcastSubtitle: Short description of the podcast - 255 character max.
